"use client";
import { useEffect,useState } from "react";
type SchoolModel={low:number;mid:number;high:number;seats:number};
type Model={version:string;next_list_date?:string;announcement?:string;notification?:{id:string;body:string;created_at:string};schools:Record<string,SchoolModel>};
const labels:Record<string,string>={kenitra:"القنيطرة",settat:"سطات",casablanca:"الدار البيضاء",tanger:"طنجة",agadir:"أكادير",fes:"فاس",marrakech:"مراكش",oujda:"وجدة",eljadida:"الجديدة",benimellal:"بني ملال",elhajeb:"الحاجب",alhoceima:"الحسيمة",dakhla:"الداخلة"};
export default function AdminDashboard({email}:{email:string}){
  const [model,setModel]=useState<Model|null>(null);const [state,setState]=useState("loading");
  const [visitors,setVisitors]=useState({total:0,online:0,today:0});
  const [notificationText,setNotificationText]=useState("");
  const activeNetworks=7;
  const schoolCount=model?Object.keys(model.schools).length:0;
  useEffect(()=>{fetch("/api/model",{cache:"no-store"}).then(r=>r.json()).then(m=>{setModel(m);setState("ready")}).catch(()=>setState("error"))},[]);
  useEffect(()=>{const refresh=()=>fetch(`/api/visitors?t=${Date.now()}`,{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(setVisitors).catch(()=>{});refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer)},[]);
  const updateSchool=(key:string,field:keyof SchoolModel,value:number)=>setModel(current=>current?{...current,schools:{...current.schools,[key]:{...current.schools[key],[field]:value}}}:current);
  async function save(){if(!model)return;setState("saving");const next={...model,version:new Date().toISOString().slice(0,16).replace(/[-T:]/g,".")};const response=await fetch("/api/model",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(response.ok){setState("saved");setModel(next)}else{const body=await response.json().catch(()=>({error:"Erreur inconnue"}));setState(`error:${body.error||response.status}`)}}
  async function sendNotification(){if(!model||!notificationText.trim())return;setState("sending");const now=new Date().toISOString();const next={...model,version:now.slice(0,16).replace(/[-T:]/g,"."),announcement:notificationText.trim(),notification:{id:now,body:notificationText.trim(),created_at:now}};const response=await fetch("/api/model",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(response.ok){setState("sent");setModel(next);setNotificationText("")}else{const body=await response.json().catch(()=>({error:"Erreur inconnue"}));setState(`error:${body.error||response.status}`)}}
  if(!model)return <main className="admin-loading">Chargement…</main>;
  return <main className="admin-shell" dir="rtl">
    <header><div><span>ORIENTATION LGOSS</span><h1>لوحة إدارة التوقعات</h1><p>{email}</p></div><a href="/">← الموقع العام</a></header>
    <section className="visitor-stats"><article><i className="live-dot"/><div><small>متصلين دابا</small><strong>{visitors.online}</strong></div><span>مباشر</span></article><article><div><small>زوار اليوم</small><strong>{visitors.today}</strong></div><span>اليوم</span></article><article><div><small>مجموع الزوار</small><strong>{visitors.total}</strong></div><span>منذ الإطلاق</span></article></section>
    <section className="admin-overview"><article><span>الشبكات المفعّلة</span><strong>{activeNetworks}</strong><p>ENCG, ENSA, ENSAM, Santé, ENS, EST, FST</p></article><article><span>مدن ENCG قابلة للتعديل</span><strong>{schoolCount}</strong><p>يمكنك تبديل الرتب المتشائمة، المركزية والمتفائلة مباشرة.</p></article><article><span>حالة المنصة</span><strong>جاهزة</strong><p>الموقع العمومي كيعرض آخر نسخة منشورة وكيحدّث المعطيات تلقائياً.</p></article></section>
    <section className="admin-settings"><label><span>تاريخ اللائحة المقبلة</span><input type="datetime-local" value={(model.next_list_date||"").slice(0,16)} onChange={e=>setModel({...model,next_list_date:`${e.target.value}:00+01:00`})}/></label><label><span>إعلان مختصر للطلبة</span><input value={model.announcement||""} placeholder="مثال: خرجات Iteration جديدة" onChange={e=>setModel({...model,announcement:e.target.value})}/></label></section>
    <section className="admin-broadcast"><div><span>إشعار فوري للزوار</span><h2>كتب رسالة وغادي تطلع للناس اللي مفعّلين الإشعارات</h2><p>الإشعار كيوصل تقريباً فثواني قليلة للزوار المتواجدين أو اللي عندهم الإشعارات مفعّلة.</p></div><label><span>نص الإشعار</span><input value={notificationText} placeholder="مثال: خرجات لائحة جديدة، جرّب النسبة ديالك دابا" onChange={e=>setNotificationText(e.target.value)}/></label><button onClick={sendNotification} disabled={state==="sending"||!notificationText.trim()}>{state==="sending"?"جاري الإرسال…":"إرسال الإشعار الآن"}</button></section>
    <section className="admin-table"><div className="admin-row head"><b>المدينة</b><b>متشائم</b><b>مركزي</b><b>متفائل</b><b>المقاعد</b></div>{Object.entries(model.schools).map(([key,s])=><div className="admin-row" key={key}><strong>{labels[key]||key}</strong>{(["low","mid","high","seats"] as const).map(field=><input key={field} type="number" value={s[field]} onChange={e=>updateSchool(key,field,Number(e.target.value))}/>)}</div>)}</section>
    <footer><div><span className={`save-state ${state}`}>{state==="saved"?"✓ تحفظات التغييرات":state==="sent"?"✓ تسيفط الإشعار":state==="sending"?"جاري إرسال الإشعار…":state==="saving"?"جاري الحفظ…":state.startsWith("error:")?state.slice(6):"النسخة: "+model.version}</span><small>الموقع العام كيراجع الرسائل الجديدة كل 15 ثانية.</small></div><button onClick={save} disabled={state==="saving"||state==="sending"}>حفظ ونشر التحديث</button></footer>
  </main>;
}
